2018-05-05 12:10:35,077 ERROR: Exception on /static/ckeditor/plugins/imageCustomUploader/plugin.js [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-05 12:15:16,892 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:15:30,223 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:15:35,805 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:15:43,128 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:15:43,150 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:17:18,250 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:17:48,446 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:17:53,671 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:18:00,945 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-07 11:49:59,084 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:72]
2018-05-07 11:51:00,595 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:72]
2018-05-07 11:51:20,837 ERROR: Exception on /favicon.ico [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 42, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-07 11:54:46,237 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:72]
2018-05-07 11:55:44,057 ERROR: Exception on /loign [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 42, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
