2018-05-05 11:13:29,567 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:38:43,379 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:39:59,537 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 11:40:03,426 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:47:03,407 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 11:47:20,077 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:50:28,348 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:53:37,573 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 11:53:47,554 ERROR: Exception on /ckupload [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-05 11:56:03,914 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:06:50,724 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:07:31,410 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:07:47,429 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:08:38,698 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:08:50,050 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:08:50,970 ERROR: Exception on /static/ckeditor/plugins/imageCustomUploader/plugin.js [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-05 12:09:49,366 ERROR: Exception on /static [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-05 12:10:20,107 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 12:10:25,122 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
2018-05-05 12:10:34,125 INFO: Jaume Nart Baron [in /home/jaume/Flask/blogapp/app/routes.py:245]
